server:
  port: 5555
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://127.0.0.1:9000/eureka/
    # service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  application:
    name: zuul-server

zuul:
       routes:
         service-invoker:
                     path: /client/**
                     serviceId: service-invoker
