server:
  port: 7000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 10.44.2.143
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:9000/eureka/
    # service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  application:
    name: service-provider
