name: Download Docker Image
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and save image
        run: |
          docker pull mpromonet/webrtc-streamer:master-arm64
          docker save mpromonet/webrtc-streamer -o webrtc-streamer64.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webrtc-streamer-image
          path: webrtc-streamer.tar
